# Generated by Django 4.0.4 on 2022-07-15 09:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='New_word_story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, default='Новое слово', help_text='<small class="text-muted">это новое слово</small><hr><br>', max_length=50, verbose_name='новое слово')),
            ],
            options={
                'verbose_name': 'Новое слово',
                'verbose_name_plural': 'Новые слова',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='заголовок', help_text='<small class="text-muted">это наш заголовок</small><hr><br>', max_length=300, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, default='img/story/default/redefault_story.jpg', help_text='<small class="text-muted">это наш заставка</small><hr><br>', upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='Заставка:')),
                ('time_to_learn', models.IntegerField(blank=True, default='1', help_text='<small class="text-muted">это наш время на учёбу</small><hr><br>', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Время на учёбу (минут)')),
                ('description', models.TextField(blank=True, default='Описание', help_text='<small class="text-muted">это наш заголовок</small><hr><br>', verbose_name='Описание')),
                ('author', models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">автор</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор истории')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
        migrations.CreateModel(
            name='StoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Заголовок', help_text='<small class="text-muted">это наш заголовок</small><hr><br>', max_length=250, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории историй',
            },
        ),
        migrations.CreateModel(
            name='StoryRaiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField(blank=True, default='0', help_text='<small class="text-muted">Оценка</small><hr><br>', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('story', models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">История</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_foodrecipes.story', verbose_name='История')),
                ('user', models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">История</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='История')),
            ],
            options={
                'verbose_name': 'Рейтинг истории',
                'verbose_name_plural': 'Рейтинг историй',
            },
        ),
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(blank=True, default='Текст комментарий', help_text='<small class="text-muted">тексь комментария</small><hr><br>', max_length=500, verbose_name='Заголовок')),
                ('story', models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">История</small><hr><br>', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_foodrecipes.story', verbose_name='История')),
                ('user', models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">История</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий к истории',
                'verbose_name_plural': 'комментарии к историям',
            },
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ManyToManyField(blank=True, db_column='category_db_column', db_index=True, default=None, error_messages=False, help_text='<small class="text-muted">Категория</small><hr><br>', to='app_foodrecipes.storycategory', verbose_name='Категория истории'),
        ),
        migrations.AddField(
            model_name='story',
            name='new_words_story',
            field=models.ManyToManyField(blank=True, default=None, help_text='<small class="text-muted">Новые слова</small><hr><br>', to='app_foodrecipes.new_word_story', verbose_name='Новые слова'),
        ),
    ]
