# Generated by Django 4.0.4 on 2022-07-29 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_foodrecipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.SlugField(blank=True, default='', help_text='<small class="text-muted">это строка токена</small><hr><br>', max_length=500, unique=True, verbose_name='Токен')),
                ('datetime_field', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, error_messages=False, help_text='<small class="text-muted">время</small><hr><br>', null=True, verbose_name='Время создания токена')),
                ('user', models.OneToOneField(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">кому был выдан токен</small><hr><br>', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец токена')),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
                'ordering': ('datetime_field', 'user'),
            },
        ),
    ]
