# Generated by Django 4.0.4 on 2022-07-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foodrecipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'История', 'verbose_name_plural': 'Истории'},
        ),
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True, default='Описание', help_text='<small class="text-muted">это наш заголовок</small><hr><br>', null=True, verbose_name='Описание'),
        ),
    ]
