# Generated by Django 4.0.4 on 2022-07-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_foodrecipes', '0002_modeltoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelToken',
        ),
    ]
