# Generated by Django 4.0.4 on 2022-07-03 06:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_foodrecipes', '0002_alter_story_options_story_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='заголовок', help_text='<small class="text-muted">это наш заголовок</small><hr><br>', max_length=250, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории историй',
            },
        ),
        migrations.AddField(
            model_name='story',
            name='time_to_learn',
            field=models.IntegerField(blank=True, default='1', help_text='<small class="text-muted">это наш время на учёбу</small><hr><br>', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Время на учёбу (минут)'),
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_db_column', db_tablespace='category_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">Категория</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_foodrecipes.storycategory', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Категория'),
        ),
    ]
