# Generated by Django 4.0.4 on 2022-07-31 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_foodrecipes', '0003_delete_modeltoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.SlugField(blank=True, default='', help_text='<small class="text-muted">фото url</small><hr><br>', max_length=500, unique=True, verbose_name='фото url')),
                ('message', models.TextField(blank=True, default='Описание', help_text='<small class="text-muted">это наш заголовок</small><hr><br>', verbose_name='Описание')),
                ('datetime_field', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, error_messages=False, help_text='<small class="text-muted">время</small><hr><br>', null=True, verbose_name='Время создания сообщения')),
                ('user', models.OneToOneField(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">кому был выдан токен</small><hr><br>', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец токена')),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чаты',
                'ordering': ('datetime_field', 'user'),
            },
        ),
    ]
