# Generated by Django 4.0.4 on 2022-07-03 08:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_foodrecipes', '0003_storycategory_story_time_to_learn_story_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">Категория</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_foodrecipes.storycategory', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='StoryRaiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField(blank=True, default='0', help_text='<small class="text-muted">Оценка</small><hr><br>', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('story', models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">История</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_foodrecipes.story', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='История')),
                ('user', models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">История</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='История')),
            ],
            options={
                'verbose_name': 'Рейтинг истории',
                'verbose_name_plural': 'Рейтинг историй',
            },
        ),
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(blank=True, default='Текст комментарий', help_text='<small class="text-muted">тексь комментария</small><hr><br>', max_length=500, null=True, verbose_name='Заголовок')),
                ('story', models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">История</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_foodrecipes.story', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='История')),
                ('user', models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">История</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='История')),
            ],
            options={
                'verbose_name': 'Комментарий к истории',
                'verbose_name_plural': 'комментарии к историям',
            },
        ),
    ]
