# Generated by Django 4.0.4 on 2022-08-04 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foodrecipes', '0004_chat_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_model',
            name='photo',
            field=models.SlugField(blank=True, default='chat_img/default_chat.jpg', help_text='<small class="text-muted">фото url</small><hr><br>', max_length=500, verbose_name='фото url'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, default='storyimg/redefault_story.jpg', help_text='<small class="text-muted">это наш заставка</small><hr><br>', upload_to='storyimg/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='Заставка:'),
        ),
    ]
