# Generated by Django 4.0.4 on 2022-07-03 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_foodrecipes', '0004_alter_story_category_storyraiting_storycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">автор</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Автор истории'),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='user',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">История</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Пользователь'),
        ),
    ]
