# Generated by Django 4.0.4 on 2022-08-04 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_foodrecipes', '0005_alter_chat_model_photo_alter_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_model',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец сообщения'),
        ),
    ]
