# Generated by Django 4.0.4 on 2022-07-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_foodrecipes', '0006_new_word_story'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new_word_story',
            options={'verbose_name': 'Новое слово', 'verbose_name_plural': 'Новые слова'},
        ),
        migrations.AddField(
            model_name='story',
            name='new_words_story',
            field=models.ManyToManyField(blank=True, default=None, help_text='<small class="text-muted">Новые слова</small><hr><br>', null=True, to='app_foodrecipes.new_word_story', verbose_name='Новые слова'),
        ),
        migrations.AlterField(
            model_name='new_word_story',
            name='word',
            field=models.CharField(blank=True, default='новое слово', help_text='<small class="text-muted">это новое слово</small><hr><br>', max_length=50, verbose_name='новое слово'),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='story',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">История</small><hr><br>', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_foodrecipes.story', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='История'),
        ),
    ]
