# Generated by Django 4.0.4 on 2022-07-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foodrecipes', '0007_alter_new_word_story_options_story_new_words_story_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='category',
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, help_text='<small class="text-muted">Категория</small><hr><br>', null=True, to='app_foodrecipes.storycategory', verbose_name='Категория'),
        ),
    ]
